### PR TITLE
Accept any AbstractMatrix in knn (e.g. views)

### PR DESCRIPTION
**Pull request by juliohm**
A simple change to make the function work with matrix views as well.

### CODE REVIEW

**Comment by juliohm** [comment]
The build is passing. For some reason Travis got killed before it finished all the builds.

Could you please review, merge and tag? :)

**Comment by juliohm** [comment]
Added the tests. Please let me know if anything else is missing.

**Comment by KristofferC** [comment]
Looks good now!

**Comment by juliohm** [comment]
Appreciate if a version is tagged :+1:

**Comment by KristofferC** [comment]
Already tagged and METADATA PR merged.

**Pull request merged**
