### PR TITLE
Exporting NNTree in NearestNeighbors Module

### PR DESCRIPTION
**Pull request by Shushman**
I want to be able to define a member of type `NNTree` in my struct here - https://github.com/Shushman/LocalApproximationValueIteration.jl/blob/master/src/localNNValueFunctionApproximator.jl#L6

Is this the right way to do this? I am fairly new to Julia so bear with me!

### CODE REVIEW

**Comment by Shushman** [comment]
Hey @KristofferC can you help me figure out what checks are failing? It doesn't seem like this addition should break anything?

**Comment by KristofferC** [comment]
Yes, I will try look at this tomorrow.

**Comment by Shushman** [comment]
Bump! Sorry to bother, trying to get this passed so I can eventually submit another dependent package to `METADATA.jl`

**Comment by KristofferC** [comment]
You can always just write `NearestNeighbors.NNTree` so no need to wait for this PR. But 0.6 passes on Travis so  can merge this.

**Comment by Shushman** [comment]
My bad! I hadn't realized that. Thank you

**Pull request merged**
