### PR TITLE
WIP: add benchmarks

### PR DESCRIPTION
**Pull request by KristofferC**
Started on a benchmark to do the same as in: https://github.com/jlblancoc/nanoflann#21-kdtreesingleindexadaptorparamsleaf_max_size

It currently generates something like:

image

I ran this on my windows machine though and I don't trust the results from it so I will redo it from linux later.

TODO:

- [ ] Add the BallTree.
- [ ] Add leafsize markers
- [ ] Run with real data set
- [ ] Add C.I ellipsis

cc @rened, @c42f

### CODE REVIEW

**Comment by c42f** [comment]
Hey, I was on holiday - back now and just wanted to say this is great :)  I'm rather surprised that the unordered and reordered sets are so similar for small leaf sizes, I'm not sure how to interpret that yet.

I can probably arrange some real world point cloud test data if you like, though my use case is just one of many.

It would be interesting to compare directly to nanoflann, I have a set of matlab mex files which could be munged into a nanoflann C interface without too much work (mostly just by deleting a lot of guff... mex files are awful!)

**Comment by c42f** [comment]
Here's a hacked up interface over nanoflann to help with benchmarking: https://github.com/c42f/Nanoflann.jl

It's a bit rough around the edges, but my initial comparison suggests that NearestNeighbors.jl is very competitive with it for knn searches on random volumetric data (within 10% or so).  The nanoflann tree build seems almost twice as fast.

**Comment by KristofferC** [comment]
Regarding the unordered reordered difference, I also find it strange. Running a simple `@time` shows that unordered is about two times slower:

```
julia> @time idxs, dists = knn(kdtree, points, 5);
  0.397646 seconds (300.01 k allocations: 25.940 MB, 5.80% gc time)

julia> @time idxs, dists = knn(kdtree_unord, points, 5);
  0.815700 seconds (300.01 k allocations: 25.940 MB, 3.54% gc time)
```

Maybe I made some mistake in the benchmarking or `Benchmarks.jl` is doing something strange.

I got VTune and julia working and for the tree building almost all time is spent in the sorting so not sure I can improve there:

image

For fun, here is a screenshot of the info from Vtune, pretty nice!

image

When threading gets merged into base everything will get a significant speedup, see: https://github.com/KristofferC/NearestNeighbors.jl/issues/5

With 4 cores I get around 2x speedup in both searching and tree building. I don't see why I shouldn't get almost linear speedup though so this can probably be optimized further.

**Comment by KristofferC** [comment]
Thanks for making that interface to nanoflann. I will try it out!

**Comment by KristofferC** [comment]
Explicitly inlining the sorting function with `@inline` gave;

```
@time kdtree = KDTree(data; leafsize = 10)
  0.509179 seconds (100.02 k allocations: 42.726 MB, 6.77% gc time)
```

~15% speedup...
```
 0.586983 seconds (100.02 k allocations: 42.726 MB, 7.51% gc time)
```

**Comment by KristofferC** [comment]
Having some troubles compiling:

```
$ clang++-3.6 -O3 -shared -fPIC -o nanoflann.so nanoflann.cpp -I /home/kristoffer/nanoflann/include/
nanoflann.cpp:93:72: warning: use of right-shift operator ('>>') in template argument will require
      parentheses in C++11 [-Wc++11-compat]
        typedef nanoflann::L2_Simple_Adaptor<double,ArrayPointWrapper<N>> DistanceAdaptor;
                                                                       ^
nanoflann.cpp:93:75: error: use of undeclared identifier 'DistanceAdaptor'
        typedef nanoflann::L2_Simple_Adaptor<double,ArrayPointWrapper<N>> DistanceAdaptor;
                                                                          ^
nanoflann.cpp:93:90: error: expected a type
        typedef nanoflann::L2_Simple_Adaptor<double,ArrayPointWrapper<N>> DistanceAdaptor;
                                                                                         ^
nanoflann.cpp:94:53: error: use of undeclared identifier 'DistanceAdaptor'
        typedef nanoflann::KDTreeSingleIndexAdaptor<DistanceAdaptor, ArrayPointWrapper<N>, N> Tree;
                                                    ^
nanoflann.cpp:94:90: error: expected member name or ';' after declaration specifiers
        typedef nanoflann::KDTreeSingleIndexAdaptor<DistanceAdaptor, ArrayPointWrapper<N>, N> Tree;
        ~~~~~~~                                                                          ^
nanoflann.cpp:98:9: error: unknown type name 'Tree'
        Tree m_index;
        ^
1 warning and 5 errors generated.
~/.julia/v0.4/Nanoflann/src
```

**Comment by c42f** [comment]
Oops, this was only because I default to C++11 mode locally.  I pushed a one character change to also make it valid C++98 code.

**Comment by c42f** [comment]
Threading sounds interesting, though for my particular use case I'd turn it off in production.  (We typically have a huge set of embarrassingly parallel jobs, so multiprocessing is a better option for us.)

**Comment by KristofferC** [comment]
I know get: 

```julia
*** Error in `julia': free(): invalid pointer: 0x0000000002ec5e90 ***
```

Wouldn't it make more sense to give all the points at ones to nanoflann and NearestNeighbors in your benchmark?

For example, using:

```jl
function bench2(tree, points)
    knn(tree, points, 10)
end
```

and comparing against the explicit loop `bench`

```jl
julia> @time bench2(tree2, data);
  3.822778 seconds (3.00 M allocations: 320.435 MB)

julia> @time bench(tree2, data)
  4.343364 seconds (11.00 M allocations: 724.777 MB)
```

**Comment by c42f** [comment]
> Wouldn't it make more sense to give all the points at ones to nanoflann and NearestNeighbors in your benchmark?

Sure, I just totally missed that the `knn()` in NearestNeighbors could do that!

The problem with `free()` is not obvious to me, but I could easily be clobbering some memory somewhere.  Could you give some context about when the crash happens?

**Comment by KristofferC** [comment]
```
signal (4): Illegal instruction
nanoflann_free_tree at ../src/nanoflann.so (unknown line)
_free at /home/kristoffer/.julia/v0.4/Nanoflann/src/Nanoflann.jl:14
jlcall__free_21344 at  (unknown line)
jl_apply_generic at /home/kristoffer/Downloads/julia-cbe1bee3a8/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 0x7f568649446f)
jl_gc_collect at /home/kristoffer/Downloads/julia-cbe1bee3a8/bin/../lib/julia/libjulia.so (unknown line)
jl_gc_allocobj at /home/kristoffer/Downloads/julia-cbe1bee3a8/bin/../lib/julia/libjulia.so (unknown line)
jl_alloc_array_1d at /home/kristoffer/Downloads/julia-cbe1bee3a8/bin/../lib/julia/libjulia.so (unknown line)
```

For the tree building I get that NearesetNeighbors is faster? For the
```jl
@time Nanoflann.KDTree(data)
@time NearestNeighbors.KDTree(data)
```

part i get:

```jl
 0.635997 seconds (5 allocations: 176 bytes)
 0.463537 seconds (100.02 k allocations: 42.726 MB)
```

**Comment by c42f** [comment]
Strange.  I get the following timings from the benchmark.jl inside Nanoflann.jl (ubuntu 14.04, g++-4.8.4, Intel i7-2600K, ~ month old julia-0.5):

```
  0.015901 seconds (157 allocations: 10.542 KB)
  0.031707 seconds (10.02 k allocations: 4.426 MB, 8.66% gc time)
  0.219346 seconds (898.98 k allocations: 72.464 MB, 1.28% gc time)
  0.265542 seconds (1.10 M allocations: 72.464 MB, 1.43% gc time)
```

I've updated Nanoflann.jl with a proper build.jl as a bit of an exercise in understanding how to set up binary dependencies for use with Pkg.build().  In the process I did find a stupid bug in `nanoflann_free_tree()` which was asymptomatic on linux.  I fixed that, so maybe it'll work for you now...

**Comment by KristofferC** [comment]
Maybe I had a bad flag in my compiler or something, I increased the number of points by a factor of 10 and got:

for building:
```jl
  0.386216 seconds (5 allocations: 176 bytes)
  0.502229 seconds (100.02 k allocations: 42.726 MB, 2.39% gc time)
```

so nanoflann seems to build significantly faster. Maybe I could ccall into a sorting algorithm written in c and see if it makes stuff faster...

For knn (where I did not use the explicit loop for NearestNeighbors):
```jl
  7.804005 seconds (9.00 M allocations: 724.777 MB, 5.68% gc time)
  4.348951 seconds (3.00 M allocations: 320.435 MB, 11.74% gc time)
```

I tried to call nanoflann with a matrix of query points to get a fair comparison but I get:
```
julia> @time foo = bench2(tree1, data)
ERROR: Error in nanoflann_knn
 in knn at /home/kristoffer/.julia/v0.4/Nanoflann/src/Nanoflann.jl:29
 in bench2 at /home/kristoffer/.julia/v0.4/Nanoflann/test/benchmark.jl:12
```

**Comment by c42f** [comment]
> ERROR: Error in nanoflann_knn

This is due to dimension mismatch - `Nanoflann.knn()` was still expecting a single point.  I've upgraded it to allow multiple points.  (The API is still slightly different since I put all the results into a single array rather than an array of arrays.)

**Comment by KristofferC** [comment]
Closed by #30

**Pull request closed without merging**
