### PR TITLE
Added sparse vector support to BruteTree and efficient code to Distance.evaluate for sparse vectors

### PR DESCRIPTION
**Pull request by AsafManela**
BruteTree did not previously work on vectors of SparseVectors.
For sparse data it takes now much less time to build the tree and slightly less time to run knn.

### CODE REVIEW

**Comment by KristofferC** [comment]
Hello, and thanks for your PR.

I wonder, shouldn't this be a PR against https://github.com/JuliaStats/Distances.jl? The reason I am thinking that is because this is only adding functionality to the Distances namespace and if it is merged there, then everyone who is using Distances will get the benefit of this PR.

**Comment by AsafManela** [comment]
I was on the fence about it myself, but NearestNeighbors.jl needs an
implementation of show that does not take length from the static type, and
it uses its own Distances.evaluate with the doend boolean.
What do you think?

**Comment by KristofferC** [comment]
I'm still not convinced this belongs here. For any dimension sizes where using a Sparse Vector makes sense, all the trees here will be useless (not provide any benefit over brute searching). And the brute tree here exists mostly as a way of comparing performance against the real trees. What is your use case for this?

**Comment by AsafManela** [comment]
I need to run knn on roughly 1,000 sparse vectors each of dimension about 100,000. Sparsity is upward of 90%. Am I missing an already existing and simpler way to do this?
I first looked at kNN.jl but that package seems unmaintained, so I thought this one supersedes it.

**Pull request closed without merging**
