### PR TITLE
Replace AbstractFloat with Real, working on #13

### PR DESCRIPTION
**Pull request by tlnagy**
Went through and replaced the `AbstractFloat` type with `Real`. Still need to implement new tests.

### CODE REVIEW

**Comment by KristofferC** [comment]
Thanks for looking into this. I believe `@testloop` got merged into `@testset` at https://github.com/IainNZ/BaseTestNext.jl so we should update those.

**Comment by tlnagy** [comment]
Yup. I saw that too. I'll open a new PR for that and then rebase this.

**Comment by tlnagy** [comment]
Where would you recommend putting test cases for integers? In `test/test_monkey.jl`?

**Comment by KristofferC** [comment]
For deterministic tests maybe either in the know or in range test file. The monkey file is mostly for "random" test.

**Comment by tlnagy** [comment]
Okay. I'm getting the following error when using my example from #13:

```{.julia}
data = rand(1:4, (10, 10^4))
balltree = BallTree(data, Hamming())
```

```{.julia}
LoadError: InexactError()
while loading In[6], in expression starting on line 2

 in generic_scale! at linalg/generic.jl:12
 in create_bsphere at /Users/tamasnagy/.julia/v0.4/NearestNeighbors/src/hyperspheres.jl:33
 in build_BallTree at /Users/tamasnagy/.julia/v0.4/NearestNeighbors/src/ball_tree.jl:98
 in build_BallTree at /Users/tamasnagy/.julia/v0.4/NearestNeighbors/src/ball_tree.jl:113 (repeats 10 times)
 in BallTree at /Users/tamasnagy/.julia/v0.4/NearestNeighbors/src/ball_tree.jl:67
```

Which I tracked down to here: https://github.com/JuliaLang/julia/issues/12912. I'm using 0.4.1 which doesn't have this patch (https://github.com/JuliaLang/julia/commit/ab0db5ce925b330f1093ceb412e8ea84b5d46344) yet.

**Comment by KristofferC** [comment]
I guess the hyper spheres are created with Int parameter so that the center and radius are of integer type. These will of course not in general be integral even if the input data is integers. 

For input data of integer the type of the hyper spheres should probably just be float64s.

**Pull request closed without merging**
